spring.application.name=crumbs

# 1. Configuración de base de datos persistente
# Esto creará un archivo llamado 'crumbs_db.mv.db' en la carpeta raíz de tu proyecto
spring.datasource.url=jdbc:h2:file:./data/crumbs_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Activo H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Activo JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
